name: Auto-merge registrator PRs after 10 minutes

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  issues: read

concurrency:
  group: timed-automerge-${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v2

      - name: Merge after 10 minutes (if PR matches format)
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}

          MIN_AGE_MINUTES: "10"

          # Optional extra guard; set "" to disable
          HEAD_PREFIX: "registrator/"

          # Format guards
          TITLE_REGEX: '^New version:\s+.+\sv[0-9]'
          COMMIT_REGEX: '(?m)^Commit:\s*[0-9a-f]{7,40}\s*$'

          # squash | merge | rebase
          MERGE_METHOD: "squash"

          # best-effort delete the PR branch after merging
          DELETE_BRANCH: "true"
        run: |
          julia <<'JL'
          using Dates

          # JSON3 only used to read GitHub event + API JSON
          try
            using JSON3
          catch
            import Pkg
            Pkg.add("JSON3")
            using JSON3
          end

          repo = ENV["REPO"]
          ev   = get(ENV, "GITHUB_EVENT_NAME", "")
          event = JSON3.read(read(ENV["GITHUB_EVENT_PATH"], String))

          pr = if ev == "pull_request_target"
            Int(event["pull_request"]["number"])
          elseif ev == "issue_comment" && haskey(event["issue"], "pull_request")
            Int(event["issue"]["number"])
          else
            println("No PR context; exiting.")
            exit(0)
          end

          head_prefix  = get(ENV, "HEAD_PREFIX", "")
          title_re     = Regex(get(ENV, "TITLE_REGEX", "^New version:"))
          commit_re    = Regex(get(ENV, "COMMIT_REGEX", "(?m)^Commit:"))
          min_age      = Minute(parse(Int, get(ENV, "MIN_AGE_MINUTES", "10")))
          merge_method = get(ENV, "MERGE_METHOD", "squash")
          delete_branch = get(ENV, "DELETE_BRANCH", "true") == "true"

          ghjson(cmd::Cmd) = JSON3.read(read(cmd, String))

          function eligible(prj)
            prj["state"] == "open" || return false
            prj["draft"] == true && return false
            prj["base"]["ref"] == "main" || return false
            prj["head"]["repo"]["full_name"] == repo || return false
            !isempty(head_prefix) && !startswith(String(prj["head"]["ref"]), head_prefix) && return false
            occursin(title_re, String(prj["title"])) || return false
            return true
          end

          function first_comment_has_commit()
            cs = collect(ghjson(`gh api repos/$repo/issues/$pr/comments?per_page=100`))
            isempty(cs) && return false
            sort!(cs, by = c -> String(c["created_at"])) # ISO timestamps sort correctly
            return occursin(commit_re, String(cs[1]["body"]))
          end

          prj = ghjson(`gh api repos/$repo/pulls/$pr`)
          eligible(prj) || (println("PR #$pr not eligible; exiting."); exit(0))
          first_comment_has_commit() || (println("PR #$pr missing initial Commit: comment; exiting."); exit(0))

          created = replace(String(prj["created_at"]), "Z" => "")
          created = split(created, ".")[1]
          created_dt = DateTime(created, dateformat"yyyy-mm-ddTHH:MM:SS")

          target = created_dt + min_age
          nowdt  = now()
          if nowdt < target
            s = ceil(Int, Dates.value(target - nowdt) / 1000)
            println("Waiting $s seconds...")
            sleep(s)
          end

          # Re-check right before merge
          prj = ghjson(`gh api repos/$repo/pulls/$pr`)
          eligible(prj) || (println("PR #$pr no longer eligible; exiting."); exit(0))
          first_comment_has_commit() || (println("PR #$pr no longer matches comment rule; exiting."); exit(0))

          sha = String(prj["head"]["sha"])
          println("Merging PR #$pr ($merge_method) at $sha")
          run(`gh api -X PUT repos/$repo/pulls/$pr/merge -f merge_method=$merge_method -f sha=$sha`)

          if delete_branch
            ref = String(prj["head"]["ref"])
            encoded = replace(ref, "/" => "%2F")
            try
              run(`gh api -X DELETE repos/$repo/git/refs/heads/$encoded`)
            catch
              println("Branch delete failed (ignored).")
            end
          end
          JL
