name = "ITensorRegistry"
uuid = "c4d53e37-7e0e-4be9-ba6f-c27e01f48020"
repo = "https://github.com/ITensor/ITensorRegistry"
description = "Private registry for unreleased or unfinished ITensors packages"

[packages]
42b3faec-625b-4613-8ddc-352bf9672b8d = { name = "UnspecifiedTypes", path = "U/UnspecifiedTypes" }
4a4adec5-520f-4750-bb37-d5e66b4ddeb2 = { name = "BroadcastMapConversion", path = "B/BroadcastMapConversion" }
7e5a90cf-f82e-492e-a09b-e3e26432c138 = { name = "TypeParameterAccessors", path = "T/TypeParameterAccessors" }
