name = "ITensorRegistry"
uuid = "c4d53e37-7e0e-4be9-ba6f-c27e01f48020"
repo = "https://github.com/ITensor/ITensorRegistry"
description = "Private registry for unreleased or unfinished ITensors packages"

[packages]
0d5efcca-f356-4864-8770-e1ed8d78f208 = { name = "SparseArraysBase", path = "S/SparseArraysBase" }
1dc1fb26-a137-4954-ae60-1bd4106e95ad = { name = "ITensorInfiniteMPS", path = "I/ITensorInfiniteMPS" }
2c2a8ec4-3cfc-4276-aa3e-1307b4294e58 = { name = "NestedPermutedDimsArrays", path = "N/NestedPermutedDimsArrays" }
2c9a651f-6452-4ace-a6ac-809f4280fbb4 = { name = "BlockSparseArrays", path = "B/BlockSparseArrays" }
3ce3220d-c6cb-4fcd-b3c1-56d9c50edbe5 = { name = "NewPkg", path = "N/NewPkg" }
3d388ab1-018a-49f4-ae50-18094d5f71ea = { name = "ITensorPkgSkeleton", path = "I/ITensorPkgSkeleton" }
42b3faec-625b-4613-8ddc-352bf9672b8d = { name = "UnspecifiedTypes", path = "U/UnspecifiedTypes" }
43c9e47c-e622-40fb-bf18-a09fc8c466b6 = { name = "UnallocatedArrays", path = "U/UnallocatedArrays" }
4795dd04-0d67-49bb-8f44-b89c448a1dc7 = { name = "ITensorBase", path = "I/ITensorBase" }
4a4adec5-520f-4750-bb37-d5e66b4ddeb2 = { name = "BroadcastMapConversion", path = "B/BroadcastMapConversion" }
60cbd0c0-df58-4cb7-918c-6f5607b73fde = { name = "NamedDimsArrays", path = "N/NamedDimsArrays" }
680c2d7c-f67a-4cc9-ae9c-da132b1447a5 = { name = "BackendSelection", path = "B/BackendSelection" }
68bd88dc-f39d-4e12-b2ca-f046b68fcc6a = { name = "TensorAlgebra", path = "T/TensorAlgebra" }
6b6dea30-58b3-414c-b7c7-5c6ea5923b3e = { name = "ITensorCorrelators", path = "I/ITensorCorrelators" }
6c5e35bf-e59e-4898-b73c-732dcc4ba65f = { name = "DerivableInterfaces", path = "D/DerivableInterfaces" }
74fd4be6-21e2-4f6f-823a-4360d37c7a77 = { name = "DiagonalArrays", path = "D/DiagonalArrays" }
7e5a90cf-f82e-492e-a09b-e3e26432c138 = { name = "TypeParameterAccessors", path = "T/TypeParameterAccessors" }
826dd319-6fd5-459a-a990-3a4f214664bf = { name = "QuantumOperatorDefinitions", path = "Q/QuantumOperatorDefinitions" }
a07dfc7f-7d04-4eb5-84cc-a97f051f655a = { name = "Derive", path = "D/Derive" }
be4d3e89-4dcc-4f34-a73c-076e5da60062 = { name = "TestPackage", path = "T/TestPackage" }
c7a6d0f7-daa6-4368-ba67-89ed64127c3b = { name = "QuantumOperatorAlgebra", path = "Q/QuantumOperatorAlgebra" }
e204200e-d7ba-4b7e-bfa9-053a2e530198 = { name = "WidenableArrays", path = "W/WidenableArrays" }
e2de450a-8a67-46c7-b59c-01d5a3d041c5 = { name = "GradedUnitRanges", path = "G/GradedUnitRanges" }
ebd9b9da-f48d-417c-9660-449667d60261 = { name = "MapBroadcast", path = "M/MapBroadcast" }
f856a3a6-4152-4ec4-b2a7-02c1a55d7993 = { name = "LabelledNumbers", path = "L/LabelledNumbers" }
f8a8ad64-adbc-4fce-92f7-ffe2bb36a86e = { name = "SymmetrySectors", path = "S/SymmetrySectors" }
f9fb0810-3969-484c-b54e-62935ba8ba22 = { name = "ITensorEntropyTools", path = "I/ITensorEntropyTools" }
fd9b415b-e710-4e2a-b407-cba023081494 = { name = "ITensorQuantumOperatorDefinitions", path = "I/ITensorQuantumOperatorDefinitions" }
